/**
 * PDF Export Utility for Chat History
 * Uses browser's print functionality for clean PDF export
 */

export function exportChatToPDF(messages, title = 'Chat History') {
  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }

  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  // Generate HTML content
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title} - StudySpace Export</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
          color: #1a1a1a;
          line-height: 1.6;
        }
        
        .header {
          text-align: center;
          padding-bottom: 30px;
          border-bottom: 2px solid #8C1D40;
          margin-bottom: 30px;
        }
        
        .header h1 {
          color: #8C1D40;
          font-size: 24px;
          margin-bottom: 8px;
        }
        
        .header .subtitle {
          color: #666;
          font-size: 14px;
        }
        
        .header .date {
          color: #999;
          font-size: 12px;
          margin-top: 8px;
        }
        
        .message {
          margin-bottom: 24px;
          page-break-inside: avoid;
        }
        
        .message-header {
          display: flex;
          align-items: center;
          gap: 10px;
          margin-bottom: 8px;
        }
        
        .avatar {
          width: 32px;
          height: 32px;
          border-radius: 8px;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: bold;
          color: white;
          font-size: 14px;
        }
        
        .avatar.assistant {
          background: #8C1D40;
        }
        
        .avatar.user {
          background: #14b8a6;
        }
        
        .sender {
          font-weight: 600;
          font-size: 14px;
        }
        
        .content {
          padding-left: 42px;
          white-space: pre-wrap;
          font-size: 14px;
          color: #333;
        }
        
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #eee;
          text-align: center;
          color: #999;
          font-size: 11px;
        }
        
        @media print {
          body {
            padding: 20px;
          }
          
          .message {
            page-break-inside: avoid;
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>StudySpace - WPC300</h1>
        <div class="subtitle">Problem Solving and Actionable Analytics</div>
        <div class="date">Exported on ${currentDate}</div>
      </div>
      
      <div class="messages">
        ${messages.map(msg => `
          <div class="message">
            <div class="message-header">
              <div class="avatar ${msg.type}">
                ${msg.type === 'assistant' ? '✦' : 'U'}
              </div>
              <span class="sender">${msg.type === 'assistant' ? 'AI Assistant' : 'You'}</span>
            </div>
            <div class="content">${escapeHtml(msg.content)}</div>
          </div>
        `).join('')}
      </div>
      
      <div class="footer">
        <p>Generated by StudySpace • Arizona State University • W. P. Carey School of Business</p>
      </div>
    </body>
    </html>
  `;

  // Write content and trigger print
  printWindow.document.write(htmlContent);
  printWindow.document.close();
  
  // Wait for content to load, then print
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };
}

function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Export chat as JSON file
 */
export function exportChatToJSON(messages, filename = 'chat-history') {
  const data = {
    exported_at: new Date().toISOString(),
    course: 'WPC300 - Problem Solving and Actionable Analytics',
    messages: messages.map(msg => ({
      type: msg.type,
      content: msg.content,
      timestamp: msg.timestamp
    }))
  };

  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export chat as plain text
 */
export function exportChatToText(messages, filename = 'chat-history') {
  const header = `StudySpace Chat Export
WPC300 - Problem Solving and Actionable Analytics
Exported: ${new Date().toLocaleString()}
${'='.repeat(50)}

`;

  const content = messages.map(msg => {
    const sender = msg.type === 'assistant' ? 'AI Assistant' : 'You';
    return `[${sender}]\n${msg.content}\n`;
  }).join('\n---\n\n');

  const footer = `\n${'='.repeat(50)}
Generated by StudySpace
Arizona State University • W. P. Carey School of Business`;

  const blob = new Blob([header + content + footer], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
